# Pandas Tutorial

## Imports

In [24]:
import numpy as np
import pandas as pd

## Basics

In [25]:
df = pd.read_csv('./dataset/dataset.csv')

In [26]:
df.head()

,Unnamed: 0,attributes,credits,crn,levels,meeting_days,meeting_instructors,meeting_place,meeting_sched_type,meeting_time,meeting_type,number,section,subject,title
0,0,Lower Division,0.0,56742,Graduate|Professional|Undergraduate,T,Karen Marais,Wilmeth Active Learning Center 1018,Lecture,3:30 pm - 4:20 pm,Class,AAE 20000,001,AAE,Undergraduate Sophomore Seminar
1,1,Lower Division,3.0,67031,Graduate|Professional|Undergraduate,TR,Shaoshuai Mou,Physics Building 114,Lecture,4:30 pm - 5:45 pm,Class,AAE 20300,002,AAE,Aeromechanics I
2,2,Lower Division,3.0,13363,Graduate|Professional|Undergraduate,MWF,Smriti Nandan Paul,Wilmeth Active Learning Center 1055,Lecture,7:30 am - 8:20 am,Class,AAE 20300,003,AAE,Aeromechanics I
3,3,Lower Division,3.0,10002,Graduate|Professional|Undergraduate,MWF,Ritwik Bandyopadhyay,Wetherill Lab of Chemistry 172,Lecture,8:30 am - 9:20 am,Class,AAE 20400,001,AAE,Aeromechanics II
4,4,Lower Division,1.0,10006,Graduate|Professional|Undergraduate,W,Ricardo Jose Gomez|Waterloo Tsutsui,Neil Armstrong Hall of Engr 3106,Laboratory,11:30 am - 1:20 pm,Class,AAE 20401,001,AAE,Aeromechanics II Laboratory

In [27]:
df.columns

Index(['Unnamed: 0', 'attributes', 'credits', 'crn', 'levels', 'meeting_days',
       'meeting_instructors', 'meeting_place', 'meeting_sched_type',
       'meeting_time', 'meeting_type', 'number', 'section', 'subject',
       'title'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16807 entries, 0 to 16806
Data columns (total 15 columns):
Unnamed: 0             16807 non-null int64
attributes             12435 non-null object
credits                16807 non-null float64
crn                    16807 non-null int64
levels                 16807 non-null object
meeting_days           8704 non-null object
meeting_instructors    16353 non-null object
meeting_place          8704 non-null object
meeting_sched_type     16807 non-null object
meeting_time           8704 non-null object
meeting_type           16807 non-null object
number                 16807 non-null object
section                16807 non-null object
subject                16807 non-null object
title                  16807 non-null object
dtypes: float64(1), int64(2), object(12)
memory usage: 1.9+ MB

In [29]:
df.describe()

         Unnamed: 0       credits           crn
count  16807.000000  16807.000000  16807.000000
mean    8403.000000      1.550782  27950.230559
std     4851.907323      1.550806  17098.064428
min        0.000000      0.000000  10002.000000
25%     4201.500000      1.000000  15643.500000
50%     8403.000000      1.000000  21214.000000
75%    12604.500000      3.000000  38041.500000
max    16806.000000     16.000000  72311.000000

In [30]:
df.credits.min()

0.0

### What is the subject with most sections?

In [10]:
df.subject.value_counts()

BIOL    916
ECE     781
CHM     688
ME      570
MA      567
EPCS    530
ENGL    482
CS      464
PHYS    383
NUR     374
MGMT    326
AT      306
PSY     302
CE      293
SLHS    278
COM     275
AAE     269
CHE     263
EDCI    251
BME     241
STAT    239
TECH    236
ENGR    220
CNIT    210
AD      208
AGRY    201
MSE     199
CGT     196
EAPS    187
EDPS    186
       ...
ASTR     15
MFET     15
ILS      13
CEM      13
MSL      13
ARAB     12
CLPH     11
NUPH     11
FVS      11
LATN     11
AAS      10
CLCS      9
SFS       8
NS        8
IDIS      8
CAND      6
SYS       6
LALS      6
PTGS      6
SCI       6
GREK      4
HEBR      4
HSOP      4
PTEC      4
ASAM      3
REL       3
JWST      3
GSLA      3
CDIS      1
MARS      1
Name: subject, Length: 137, dtype: int64

### What is hardest class (by credit)?

In [13]:
df.sort_values(by='credits', ascending=False).head()

,Unnamed: 0,attributes,credits,crn,levels,meeting_days,meeting_instructors,meeting_place,meeting_sched_type,meeting_time,meeting_type,number,section,subject,title
7694,7694,Credit By Exam|Full-Time Privileges|Student Te...,16.0,16555,Graduate|Professional|Undergraduate,NaN,Jennifer Elaine Smith|Kharon D Grimmet,NaN,Experiential,NaN,Class,EDPS 49800,004,EDPS,Spvsd Tch Mld & Intense Dis
7692,7692,Credit By Exam|Full-Time Privileges|Student Te...,16.0,16547,Graduate|Professional|Undergraduate,NaN,Kharon D Grimmet|Jennifer Elaine Smith,NaN,Experiential,NaN,Class,EDPS 49800,002,EDPS,Spvsd Tch Mild Dis
10007,10007,Upper Division|Variable Title,16.0,13624,Graduate|Professional|Undergraduate,NaN,Megan L Purcell,NaN,Experiential,NaN,Class,HDFS 45000,002,HDFS,Supervised Teaching In Inclusive Programs For ...
7485,7485,Credit By Exam|Student Teaching|Upper Division...,16.0,16540,Graduate|Professional|Undergraduate,NaN,Paul A Asunda,NaN,Experiential,NaN,Class,EDCI 49800,G01,EDCI,Supvsd Tch Tech Educ
7477,7477,Upper Division,16.0,68577,Graduate|Professional|Undergraduate,NaN,Jennifer W Barce,NaN,Experiential,NaN,Class,EDCI 49600,003,EDCI,Student Teaching In The Elementary School

### How many classes have sections on saturday?

In [20]:
df[df.meeting_days == 'S'].count()

Unnamed: 0             28
attributes             22
credits                28
crn                    28
levels                 28
meeting_days           28
meeting_instructors    28
meeting_place          28
meeting_sched_type     28
meeting_time           28
meeting_type           28
number                 28
section                28
subject                28
title                  28
dtype: int64

### Which class has the most sections?

In [31]:
df.groupby('number').agg('count').sort_values('title', ascending=False).head()

,Unnamed: 0,attributes,credits,crn,levels,meeting_days,meeting_instructors,meeting_place,meeting_sched_type,meeting_time,meeting_type,section,subject,title
number,,,,,,,,,,,,,,
CHM 11500,226,226,226,226,226,226,226,226,226,226,226,226,226,226
BIOL 49400,189,189,189,189,189,0,185,0,189,0,189,189,189,189
ENGL 10600,165,165,165,165,165,147,165,147,165,147,165,165,165,165
BIOL 49900,140,140,140,140,140,0,140,0,140,0,140,140,140,140
ME 69900,124,0,124,124,124,0,124,0,124,0,124,124,124,124

### More questions

* What subjects have classes on saturdays?
* What is the most popular class time?
* I need one credit hour class in CS. What can I pick?

In [33]:
df[(df.credits == 1) & (df.subject == 'CS')]

,Unnamed: 0,attributes,credits,crn,levels,meeting_days,meeting_instructors,meeting_place,meeting_sched_type,meeting_time,meeting_type,number,section,subject,title
5623,5623,Lower Division,1.0,13498,Graduate|Professional|Undergraduate,W,Philip M Leblanc,Felix Haas Hall G066,Lecture,12:30 pm - 1:20 pm,Class,CS 19100,LC1,CS,Freshman Resources Seminar
5624,5624,Lower Division,1.0,13497,Graduate|Professional|Undergraduate,T,Ranjani L Rao,Hicks Undergraduate Library G980D,Lecture,12:30 pm - 1:20 pm,Class,CS 19100,LC2,CS,Freshman Resources Seminar
5625,5625,Lower Division,1.0,13500,Graduate|Professional|Undergraduate,T,Amanda J Waszczuk,Hicks Undergraduate Library G980D,Lecture,8:30 am - 9:20 am,Class,CS 19100,LC3,CS,Freshman Resources Seminar
5626,5626,Lower Division,1.0,13496,Graduate|Professional|Undergraduate,T,Kathryn B Van Ness,Hicks Undergraduate Library G980D,Lecture,9:30 am - 10:20 am,Class,CS 19100,LC4,CS,Freshman Resources Seminar
5627,5627,Lower Division,1.0,13495,Graduate|Professional|Undergraduate,T,Faith C Giordano,Hicks Undergraduate Library G980D,Lecture,3:30 pm - 4:20 pm,Class,CS 19100,LE5,CS,Freshman Resources Seminar
5628,5628,Lower Division,1.0,16993,Graduate|Professional|Undergraduate,F,Kevin B Jones,Hicks Undergraduate Library G980D,Lecture,11:30 am - 12:20 pm,Class,CS 19100,LE6,CS,Freshman Resources Seminar
5629,5629,Lower Division,1.0,16994,Graduate|Professional|Undergraduate,F,Kevin B Jones,Hicks Undergraduate Library G980D,Lecture,12:30 pm - 1:20 pm,Class,CS 19100,LE7,CS,Freshman Resources Seminar
5630,5630,Lower Division,1.0,13499,Graduate|Professional|Undergraduate,R,Kimberly Anne Rechkemmer,Hicks Undergraduate Library G980D,Lecture,3:30 pm - 4:20 pm,Class,CS 19100,LE8,CS,Freshman Resources Seminar
5631,5631,Lower Division,1.0,12522,Graduate|Professional|Undergraduate,R,Marsha Beth Towne Rhees,Hicks Undergraduate Library G980D,Lecture,12:30 pm - 1:20 pm,Class,CS 19100,LE9,CS,Freshman Resources Seminar
5632,5632,Lower Division,1.0,21323,Graduate|Professional|Undergraduate,R,Christopher John Enright|Lauren Christina Lum,Robert Heine Pharmacy Building 172,Lecture,1:30 pm - 2:20 pm,Class,CS 19300,LE1,CS,Tools
5633,5633,Lower Division,1.0,10930,Graduate|Professional|Undergraduate,T,Christopher John Enright|Lauren Christina Lum,Robert Heine Pharmacy Building 172,Lecture,1:30 pm - 2:20 pm,Class,CS 19300,LE2,CS,Tools
5634,5634,Lower Division,1.0,11042,Graduate|Professional|Undergraduate,W,Noah Louis Alderton|Albert Lee Zhong,Wetherill Lab of Chemistry 172,Lecture,3:30 pm - 4:20 pm,Class,CS 19300,LE3,CS,Tools
5635,5635,Lower Division,1.0,11105,Graduate|Professional|Undergraduate,F,Noah Louis Alderton|Albert Lee Zhong,Wetherill Lab of Chemistry 172,Lecture,3:30 pm - 4:20 pm,Class,CS 19300,LE4,CS,Tools
5728,5728,Lower Division,1.0,68697,Graduate|Professional|Undergraduate,W,Sally L Luzader,Lawson Computer Science Bldg B151,Lecture,11:30 am - 12:20 pm,Class,CS 29100,LE1,CS,Sophomore Development Seminar
5729,5729,Lower Division,1.0,13219,Graduate|Professional|Undergraduate,W,Sally L Luzader,Lawson Computer Science Bldg B151,Lecture,12:30 pm - 1:20 pm,Class,CS 29100,LE2,CS,Sophomore Development Seminar
5759,5759,Upper Division,1.0,12735,Graduate|Professional|Undergraduate,NaN,Jawad A Raheel,NaN,Distance Learning,NaN,Class,CS 38003,LE1,CS,Python Programming
5773,5773,Upper Division|Variable Title,1.0,18343,Graduate|Professional|Undergraduate,R,Ninghui Li,Lawson Computer Science Bldg B155,Laboratory,6:00 pm - 7:50 pm,Class,CS 39000,CP1,CS,Competitive Programming I
5774,5774,Upper Division|Variable Title,1.0,15662,Graduate|Professional|Undergraduate,R,Gustavo Rodriguez-Rivera,Lawson Computer Science Bldg B158,Laboratory,6:00 pm - 7:50 pm,Class,CS 39000,CP2,CS,Competitive Programming II
5775,5775,Upper Division|Variable Title,1.0,16637,Graduate|Professional|Undergraduate,R,Gustavo Rodriguez-Rivera,Lawson Computer Science Bldg B158,Laboratory,6:00 pm - 7:50 pm,Class,CS 39000,CP3,CS,Competitive Programming III
5776,5776,Upper Division|Variable Title,1.0,20338,Graduate|Professional|Undergraduate,W,Gustavo Rodriguez-Rivera,Lawson Computer Science Bldg B131,Laboratory,3:30 pm - 5:20 pm,Class,CS 39000,L01,CS,Virtual Reality Technologies
5777,5777,Upper Division|Variable Title,1.0,20339,Graduate|Professional|Undergraduate,R,Gustavo Rodriguez-Rivera,Lawson Computer Science Bldg B131,Laboratory,1:30 pm - 3:20 pm,Class,CS 39000,L02,CS,Virtual Reality Technologies
5778,5778,Upper Division|Variable Title,1.0,20201,Graduate|Professional|Undergraduate,T,Hubert E Dunsmore|Nisarg Kolhe,Stanley Coulter Hall 239,Lecture,1:30 pm - 2:20 pm,Class,CS 39000,LE1,CS,Web Application Development
5782,5782,Upper Division|Variable Title,1.0,19354,Graduate|Professional|Undergraduate,M,Lillian D Evans|Jennifer L Montes,Lawson Computer Science Bldg B134,Lecture,3:30 pm - 4:20 pm,Class,CS 39000,SL2,CS,Service Learn Outreach
5783,5783,Upper Division,1.0,42908,Graduate|Professional|Undergraduate,TR,Sally L Luzader,Lawson Computer Science Bldg B155,Lecture,4:30 pm - 5:20 pm,Class,CS 39100,LE1,CS,Junior Resources Seminar
5810,5810,Credit By Exam|Upper Division|Variable Title,1.0,24440,Graduate|Professional|Undergraduate,NaN,Clifton W Bingham,NaN,Individual Study,NaN,Class,CS 49000,010,CS,Studies In Bias In AI
5813,5813,Credit By Exam|Upper Division|Variable Title,1.0,24505,Graduate|Professional|Undergraduate,NaN,Daisuke Kihara,NaN,Individual Study,NaN,Class,CS 49000,013,CS,NLP In Bioinformatics II
5815,5815,Credit By Exam|Upper Division|Variable Title,1.0,24793,Graduate|Professional|Undergraduate,NaN,Douglas E Comer,NaN,Individual Study,NaN,Class,CS 49000,015,CS,Operating Systems Project
5870,5870,Upper Division|Variable Title,1.0,17268,Graduate|Professional|Undergraduate,MW,Daniel G Aliaga,Lawson Computer Science Bldg B155,Lecture,3:30 pm - 4:20 pm,Class,CS 59100,RS1,CS,Res Sem First Yr Gr Student
5871,5871,Upper Division|Variable Title,1.0,34240,Graduate|Professional|Undergraduate,W,Christina L Garman,Stewart Center 050B,Lecture,4:30 pm - 5:20 pm,Class,CS 59100,SEC,CS,CERIAS Security Seminar
5872,5872,Upper Division|Variable Title,1.0,17266,Graduate|Professional|Undergraduate,MW,Lorenzo Dario Martino,Lawson Computer Science Bldg B155,Lecture,3:30 pm - 4:20 pm,Class,CS 59100,TA1,CS,Effective Teaching In CS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5966,5966,NaN,1.0,18204,Graduate|Professional|Undergraduate,NaN,Aniket Pundlik Kate,NaN,Research,NaN,Class,CS 69900,061,CS,Research PhD Thesis
5967,5967,NaN,1.0,18913,Graduate|Professional|Undergraduate,NaN,Hubert E Dunsmore,NaN,Research,NaN,Class,CS 69900,062,CS,Research PhD Thesis
5968,5968,NaN,1.0,18930,Graduate|Professional|Undergraduate,NaN,Bruno Felisberto Martins Ribeiro,NaN,Research,NaN,Class,CS 69900,063,CS,Research PhD Thesis
5969,5969,NaN,1.0,19733,Graduate|Professional|Undergraduate,NaN,Elias Bareinboim,NaN,Research,NaN,Class,CS 69900,065,CS,Research PhD Thesis
5970,5970,NaN,1.0,19922,Graduate|Professional|Undergraduate,NaN,Yiying Zhang,NaN,Research,NaN,Class,CS 69900,066,CS,Research PhD Thesis
5971,5971,NaN,1.0,19931,Graduate|Professional|Undergraduate,NaN,Jean F Honorio Carrillo,NaN,Research,NaN,Class,CS 69900,067,CS,Research PhD Thesis
5972,5972,NaN,1.0,20170,Graduate|Professional|Undergraduate,NaN,Petros S Drineas,NaN,Research,NaN,Class,CS 69900,068,CS,Research PhD Thesis
5973,5973,NaN,1.0,20213,Graduate|Professional|Undergraduate,NaN,Jeremiah Martin Blocki,NaN,Research,NaN,Class,CS 69900,069,CS,Research PhD Thesis
5974,5974,NaN,1.0,20235,Graduate|Professional|Undergraduate,NaN,He Wang,NaN,Research,NaN,Class,CS 69900,070,CS,Research PhD Thesis
5975,5975,NaN,1.0,20240,Graduate|Professional|Undergraduate,NaN,Hemanta K Maji,NaN,Research,NaN,Class,CS 69900,071,CS,Research PhD Thesis
5976,5976,NaN,1.0,20365,Graduate|Professional|Undergraduate,NaN,Saugata Basu,NaN,Research,NaN,Class,CS 69900,072,CS,Research PhD Thesis
5977,5977,NaN,1.0,20021,Graduate|Professional|Undergraduate,NaN,Roopsha Samanta,NaN,Research,NaN,Class,CS 69900,075,CS,Research PhD Thesis
5978,5978,NaN,1.0,21883,Graduate|Professional|Undergraduate,NaN,Byoungyoung Lee,NaN,Research,NaN,Class,CS 69900,077,CS,Research PhD Thesis
5979,5979,NaN,1.0,22279,Graduate|Professional|Undergraduate,NaN,Chunyi Peng,NaN,Research,NaN,Class,CS 69900,078,CS,Research PhD Thesis
5980,5980,NaN,1.0,22416,Graduate|Professional|Undergraduate,NaN,Robert D Skeel,NaN,Research,NaN,Class,CS 69900,079,CS,Research PhD Thesis
5981,5981,NaN,1.0,23031,Graduate|Professional|Undergraduate,NaN,Benjamin James Delaware,NaN,Research,NaN,Class,CS 69900,080,CS,Research PhD Thesis
5982,5982,NaN,1.0,23651,Graduate|Professional|Undergraduate,NaN,Christina L Garman,NaN,Research,NaN,Class,CS 69900,081,CS,Research PhD Thesis
5983,5983,NaN,1.0,23814,Graduate|Professional|Undergraduate,NaN,Abdolmajid Kazemian,NaN,Research,NaN,Class,CS 69900,082,CS,Research PhD Thesis
5984,5984,NaN,1.0,23815,Graduate|Professional|Undergraduate,NaN,Dongyan Xu,NaN,Research,NaN,Class,CS 69900,083,CS,Research PhD Thesis
5985,5985,NaN,1.0,24219,Graduate|Professional|Undergraduate,NaN,Ming Yin,NaN,Research,NaN,Class,CS 69900,084,CS,Research PhD Thesis
5986,5986,NaN,1.0,24226,Graduate|Professional|Undergraduate,NaN,Ming Yin,NaN,Research,NaN,Class,CS 69900,085,CS,Research PhD Thesis
5987,5987,NaN,1.0,24463,Graduate|Professional|Undergraduate,NaN,Lori J Obrien,NaN,Research,NaN,Class,CS 69900,086,CS,Research PhD Thesis
5988,5988,NaN,1.0,24476,Graduate|Professional|Undergraduate,NaN,Sanjay G Rao,NaN,Research,NaN,Class,CS 69900,087,CS,Research PhD Thesis
5989,5989,NaN,1.0,23752,Graduate|Professional|Undergraduate,NaN,Yexiang Xue,NaN,Research,NaN,Class,CS 69900,088,CS,Research PhD Thesis
5990,5990,NaN,1.0,24286,Graduate|Professional|Undergraduate,NaN,Changhee Jung,NaN,Research,NaN,Class,CS 69900,089,CS,Research PhD Thesis
5991,5991,NaN,1.0,24287,Graduate|Professional|Undergraduate,NaN,Pedro Jose Sousa Da Fonseca,NaN,Research,NaN,Class,CS 69900,090,CS,Research PhD Thesis
5992,5992,NaN,1.0,24363,Graduate|Professional|Undergraduate,NaN,Zeynel Berkay Celik,NaN,Research,NaN,Class,CS 69900,091,CS,Research PhD Thesis
5993,5993,NaN,1.0,24614,Graduate|Professional|Undergraduate,NaN,Antonio Bianchi,NaN,Research,NaN,Class,CS 69900,092,CS,Research PhD Thesis
5994,5994,NaN,1.0,24617,Graduate|Professional|Undergraduate,NaN,Jing Tian,NaN,Research,NaN,Class,CS 69900,093,CS,Research PhD Thesis
5995,5995,NaN,1.0,24667,Graduate|Professional|Undergraduate,NaN,Lin Tan,NaN,Research,NaN,Class,CS 69900,094,CS,Research PhD Thesis

## Additional Resources

* [Pandas Tutorial](https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/topic01_pandas_data_analysis/topic1_pandas_data_analysis.ipynb)